--- build/meta.go.orig	2025-06-13 15:58:00 UTC
+++ build/meta.go
@@ -1,5 +1,5 @@
 // Code generated by go generate; DO NOT EDIT.
-// This file was generated by go generate at 2024-08-12T08:54:43-07:00.
+// This file was generated by go generate at 2025-06-13T17:59:59+02:00.
 package build
 
 //go:generate go run gen.go
@@ -9,9 +9,9 @@ const (
 )
 
 const (
-	commit    = "?"
-	version   = "?"
-	buildTime = 0
+	commit = "a717e774"
+	version = "v2.3.0"
+	buildTime = %%BUILDTIME%%
 )
 
 // Commit returns the commit hash of hostd
