--- build/meta.go.orig	2025-05-08 17:38:02 UTC
+++ build/meta.go
@@ -1,5 +1,5 @@
 // Code generated by go generate; DO NOT EDIT.
-// This file was generated by go generate at 2024-08-12T08:54:43-07:00.
+// This file was generated by go generate at 2025-05-08T19:43:49+02:00.
 package build
 
 //go:generate go run gen.go
@@ -9,9 +9,9 @@ const (
 )
 
 const (
-	commit    = "?"
-	version   = "?"
-	buildTime = 0
+	commit = "13c4ba1d"
+	version = "v2.1.0"
+	buildTime = %%BUILDTIME%%
 )
 
 // Commit returns the commit hash of hostd
