--- build/meta.go.orig	2026-03-04 12:31:03 UTC
+++ build/meta.go
@@ -1,7 +1,9 @@
+// Code generated by go generate; DO NOT EDIT.
+// This file was generated by go generate at 2026-03-04T13:31:06+01:00.
 package build
 
 const (
-	commit    = "?"
-	version   = "?"
-	buildTime = 0
+	commit = "02c4e7a"
+	version = "v2.11.0"
+	buildTime = %%BUILDTIME%%
 )
