--- build/meta.go.orig	2025-04-24 05:45:48 UTC
+++ build/meta.go
@@ -1,7 +1,9 @@
+// Code generated by go generate; DO NOT EDIT.
+// This file was generated by go generate at 2025-03-11T17:25:25+01:00.
 package build
 
 const (
-	commit    = "?"
-	version   = "?"
-	buildTime = 0
+	commit = "b4e9547"
+	version = "v2.2.1"
+	buildTime = %%BUILDTIME%%
 )
