--- build/meta.go.orig	2025-06-13 16:20:41 UTC
+++ build/meta.go
@@ -1,7 +1,9 @@
+// Code generated by go generate; DO NOT EDIT.
+// This file was generated by go generate at 2025-06-13T18:21:38+02:00.
 package build
 
 const (
-	commit    = "?"
-	version   = "?"
-	buildTime = 0
+	commit = "c66b5e3"
+	version = "v2.9.0"
+	buildTime = %%BUILDTIME%%
 )
