--- build/meta.go.orig	2026-03-03 20:11:59 UTC
+++ build/meta.go
@@ -1,7 +1,9 @@
+// Code generated by go generate; DO NOT EDIT.
+// This file was generated by go generate at 2026-03-03T20:59:02+01:00.
 package build
 
 const (
-	commit    = ""
-	version   = ""
-	buildTime = 0
+	commit = "090d5f3"
+	version = "v2.7.0"
+	buildTime = %%BUILDTIME%%
 )
