--- build/meta.go.orig	2025-06-13 15:24:25 UTC
+++ build/meta.go
@@ -1,7 +1,9 @@
+// Code generated by go generate; DO NOT EDIT.
+// This file was generated by go generate at 2025-06-13T17:26:11+02:00.
 package build
 
 const (
-	commit    = ""
-	version   = ""
-	buildTime = 0
+	commit = "26c3813"
+	version = "v2.3.1"
+	buildTime = %%BUILDTIME%%
 )
