--- build/meta.go.orig	2025-05-08 16:02:02 UTC
+++ build/meta.go
@@ -1,7 +1,9 @@
+// Code generated by go generate; DO NOT EDIT.
+// This file was generated by go generate at 2025-05-08T17:51:13+02:00.
 package build
 
 const (
-	commit    = "?"
-	version   = "2.0.0"
-	buildTime = 0
+	commit = "732161e"
+	version = "v2.1.0"
+	buildTime = %%BUILDTIME%%
 )
